### PR TITLE
Initial project setup

### PR DESCRIPTION
**Pull request by Matt--**
Initial project setup.

Uses virtualenv, flask and cookiecutter to setup the framework. Runs on localhost:5000, including a db that collects user registration details. Produces a pretty Welcome screen with working links and stuff.

### CODE REVIEW

**Comment by DavePearce** [comment]
Hey,

Wow, that's quite a lot of stuff there.  That bootstrap library, that's for mobile views right?  Not sure that I would personally check in a library into the repository.  Rather I'd include instructions of how to get the library and where to put it in the README. 

D

**Comment by Matt--** [comment]
I confess I was not looking too hard at what was being bolted in, but I 
did notice the size of the files. I'll take a closer look at it tonight 
and adjust as you suggest.

**Comment by andre-geldenhuis** [comment]
Yeah all those files will be coming from the cookie cutter template.  This is basically what I have done with my projects based off it, run cookiecutter then make that my first commit to a new repo.

You are right though, it  doesn 't feel like best practise.   I am not really sure what the best approach would be.  Could be to fork the cookiecutter template and make the changes to that?  

Boostrap is used for mobile views, but it almso makes HTML layout much easier via the use of a [handy grid system](http://getbootstrap.com/examples/grid/)

**Comment by andre-geldenhuis** [comment]
Also Matt it can be helpful if you make your pull request from a branch.  After you have made a pull request from a branch, any changes you push to your branch will show up here in the conversation, effectively changing your pull request.    

David suggested git flow, and that fits quite well with that, you could make the pull request from your development branch or from a feature branch.    How does that sound?

**Comment by Matt--** [comment]
I'm open to suggestions.

At the moment I'm inclined to go with David's suggestion, remove the 
(big) libraries from git and leave instructions in the readme on where 
to find the library and where to put it. Or perhaps just link to a 
content provider.

Not sure about forking a framework, my gut is saying it's not worth it. 
Perhaps better is to just use it and adapt the results. But, my gut is 
inexperienced and has been known to be wrong...

**Comment by Matt--** [comment]
:-) sounds good.

**Comment by andre-geldenhuis** [comment]
Well you wouldn't be forking a framework, you would be forking cookiecutter which encourages forks.  For instance I should definitely fork cookiecutter-flask as I always make the same initial changes to it, namely switching from gunicorn to waitress and changing the prod and dev to both use postgress.

I think there is a good case to be made for just committing the entire cookeicutter-flask created project to the repository as Matt has done.  It does seem to be the way people use similar tools such as Django's startproject.  [An old post by Jeff Knupp on the topic](http://www.jeffknupp.com/blog/2012/02/09/starting-a-django-project-the-right-way/)

It does seem untidy to commit things like bootstrap, the other way to handle it would be to use npm to manage it, but it adds a bit of extra complexity over just committing it.  

Thoughts?

**Comment by Matt--** [comment]
> I think there is a good case to be made for just committing the entire
> cookeicutter-flask created project to the repository as Matt has done.
> It does seem to be the way people use similar tools such as Django's
> startproject. An old post by Jeff Knupp on the topic
> http://www.jeffknupp.com/blog/2012/02/09/starting-a-django-project-the-right-way/

That was a good article, thanks. At least I didn't commit the virtualenv 
:-) The discussion on Fabric was interesting too, I've installed it but 
its probably overkill for this project..

You make some good points (as does Jeff) on what should be committed. I 
will chat with David ftf tomorrow if I get the chance (tomorrow is 
pretty busy, two industry interviews and a focus group for my other 
job...). I have also looked at the github repository and noted the 
conversation logs (you mentioned these earlier). David hasn't accepted 
my commit, so I think perhaps it should be rejected in favour of 
resubmitting under a branch.

So I will leave the question of committing or separating out libraries, 
etc until later. Tonight I intend to get back up to speed on 
Flask/Django templates and mockup a dummy nzdc home page.

**Comment by andre-geldenhuis** [comment]
Ok seeing as you are splitting the pull request into two new ones, I'll close this one.  That should fix the merge conflicts (I think)  I won't accept then new pulls yet until David has reviewed them too.

Fabric is pretty neat :)  though I suspect we will probably end up using docker for deployment.

**Pull request closed without merging**
