### PR TITLE
Initial pages

### PR DESCRIPTION
**Pull request by Matt--**
Second half of the original commit. Again on a new branch.

Also includes a new commit adding a sample home page and search page stubs.

### CODE REVIEW

**Comment by andre-geldenhuis** [comment]
Ok, if I switch to this I can get it to run, and it looks like a good start :)

There are a lot of changes here, so I haven't looked through them all, a few comments though.

### Matt--  initial setup done, readme updated to reflect the start-up process

_Note: these worked after half an hour without having to do anything more. It seems the database is installed, it must be magic..._
Yeah, it will be using sqlite as the database if you are running it in dev (which it will default to unless you set an environment variable telling it not too)  There are some differences between sqlite and postgres that SQLAlchemy can't reconcile, just be aware of that.  So it does make sense to switch the dev database to a postgres container sooner rather than later.  Still getting everything going is important too.

You should probably also add the folder .directory to your gitignore file.  It looks like it is being generated by the dolphin file browser.

Not too sure it is necessary to commit the ms_hello.py and object.py files as they seem to be for testing only.

**Comment by andre-geldenhuis** [comment]
### Matt--  add sample home page, stub search pages …

I am a bit torn about switching the the font.awesome css to a CDN especially as there is a lot of other static javascript and css.  If we really don't want to host the static content we can use [Flask-S3](https://flask-s3.readthedocs.org/en/latest/) to move our static assets to amazon S3.  Probably not worth the effort though.

**Comment by Matt--** [comment]
The installed font awesome css was missing two fonts I wanted. Using a CDN was more a quick n dirty fix rather than faff about finding the right bits. That said, my inclination is to either trim the static files down to bare minimum or draw it down from somewhere else (which seemed less effort/quicker to implement in this case). Very open to your input tho'.

**Comment by Matt--** [comment]
Dave, can I get write access? It means I can sort out my own merge conflicts.

**Comment by andre-geldenhuis** [comment]
Hiya Matt, it should be possible for you to fix your merge conflicts in the pull request.

git checkout -b Matt---initialPages master

Then look into the files .gitignore, README.md and requirements.txt in a text editor and remove the merge conflict stuff and make them look how you want, then commit to your branch, that should fix the conflict here.

**Comment by Matt--** [comment]
Ta :-) will do

**Comment by andre-geldenhuis** [comment]
This should help too, http://dont-be-afraid-to-commit.readthedocs.org/en/latest/git/conflicts.html

**Comment by andre-geldenhuis** [comment]
This is good too, http://blog.michelemattioni.me/2013/01/29/what-do-i-do-when-my-pull-request-does-not-merge-automatically-in-master/

**Comment by DavePearce** [comment]
Hey Matt,

Are you making progress on handling the conflict here?

D

**Comment by Matt--** [comment]
Hi Dave,

This week has been a little odd in that I'm in my third full day at the 
Railway station campus rather than up at Kelburn. Which means Tuesday 
aside, I haven't made much progress this week. Tomorrow night is a write 
off too, but I intend to come in on Saturday or Sunday (choice depend on 
my partner...) for the day.

Regards the conflict, no problem. It just didn't occur to me to pull the 
master from elvis and merge locally. Duh...

Tuesday night and though this week I've been reading and experimenting 
with connecting to flasks db. Its going well and I'm reasonably 
optimistic that I will have a working dummy db by the end of the 
weekend. Hopefully with an html front end.

I'm up in Kelburn all day tomorrow :-)

**Comment by DavePearce** [comment]
no worries ... was wondering why I hadn't seen you around :)

D

On 19/02/15 10:43, Matt-- wrote:

> Hi Dave,
> 
> This week has been a little odd in that I'm in my third full day at the
> Railway station campus rather than up at Kelburn. Which means Tuesday
> aside, I haven't made much progress this week. Tomorrow night is a write
> off too, but I intend to come in on Saturday or Sunday (choice depend on
> my partner...) for the day.
> 
> Regards the conflict, no problem. It just didn't occur to me to pull the
> master from elvis and merge locally. Duh...
> 
> Tuesday night and though this week I've been reading and experimenting
> with connecting to flasks db. Its going well and I'm reasonably
> optimistic that I will have a working dummy db by the end of the
> weekend. Hopefully with an html front end.
> 
> I'm up in Kelburn all day tomorrow :-)
> 
> On 19/02/2015 10:28 a.m., David Pearce wrote:
> 
> > Hey Matt,
> > 
> > Are you making progress on handling the conflict here?
> > 
> > D
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > 
> > https://github.com/ElvisResearchGroup/DictionaryOfNewZealandEnglish/pull/4#issuecomment-74951581.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ElvisResearchGroup/DictionaryOfNewZealandEnglish/pull/4#issuecomment-74954450.

## 

Senior Lecturer in Computer Science,
School of Engineering and Computer Science
Victoria University of Wellington,
PO Box 600,
Wellington,
New Zealand.

Office: Cotton 231
Telephone: +64 (0)4 463 5833
URL: http://ecs.victoria.ac.nz/~djp

**Comment by Matt--** [comment]
I can close this... A version 2 pull that has had the merge conflicts resolved is ready for merging.

**Pull request closed without merging**
